name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - "/app"

  pull_request:
    branches: [ "master" ]
    paths:
      - "/app" 

env:
  LOGIN_SERVER: "acrnepatryk2bc.azurecr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker_image_name = ${{ env.LOGIN_SERVER }}/sample-app:$(date +%s) 
        docker build . --file app/Dockerfile --tag $docker_image_name
        echo $docker_image_name >> $GITHUB_ENV
    
    - name: Push the Docker image
      run: docker push ${{ env.docker_image_name }}
